#pragma once
#include "RiverFile.h"

#define FILE_PATH_RELATIVE(PATH) RiverFile::GetPathAddRootPath(PATH)

#define DEFAULT_FONT_PATH_1					FILE_PATH_RELATIVE("Fonts\\LXGWWenKai-Bold.ttf")

#define DEFAULT_SHADER_PATH_1				FILE_PATH_RELATIVE("Shaders\\Default.hlsl")
#define DEFAULT_SHADER_PATH_2				FILE_PATH_RELATIVE("Shaders\\Sky.hlsl")
#define DEFAULT_SHADER_PATH_3				FILE_PATH_RELATIVE("Shaders\\Shadows.hlsl")
#define DEFAULT_SHADER_PATH_4				FILE_PATH_RELATIVE("Shaders\\ShadowDebug.hlsl")
#define DEFAULT_SHADER_PATH_5				FILE_PATH_RELATIVE("Shaders\\Ssao.hlsl")
#define DEFAULT_SHADER_PATH_6				FILE_PATH_RELATIVE("Shaders\\DrawNormals.hlsl")
#define DEFAULT_SHADER_PATH_7				FILE_PATH_RELATIVE("Shaders\\SsaoBlur.hlsl")
#define DEFAULT_SHADER_PATH_UI				FILE_PATH_RELATIVE("Shaders\\UI.hlsl")
#define DEFAULT_SHADER_PATH_DEFAULT			FILE_PATH_RELATIVE("Shaders\\Default1.hlsl")
#define DEFAULT_SHADER_PATH_DEFAULT_RAW		FILE_PATH_RELATIVE("Shaders\\DefaultRaw.hlsl")

#define DEFAULT_TEXTURE_PATH				FILE_PATH_RELATIVE("Textures\\")
#define DEFAULT_TEXTURE_PATH_1				FILE_PATH_RELATIVE("Textures\\bricks.dds")
#define DEFAULT_TEXTURE_PATH_2				FILE_PATH_RELATIVE("Textures\\stone.dds")
#define DEFAULT_TEXTURE_PATH_3				FILE_PATH_RELATIVE("Textures\\tile.dds")
#define DEFAULT_TEXTURE_PATH_4				FILE_PATH_RELATIVE("Textures\\grass.dds")
#define DEFAULT_TEXTURE_PATH_5				FILE_PATH_RELATIVE("Textures\\water1.dds")
#define DEFAULT_TEXTURE_PATH_6				FILE_PATH_RELATIVE("Textures\\WireFence.dds")
#define DEFAULT_TEXTURE_PATH_7				FILE_PATH_RELATIVE("Textures\\bricks3.dds")
#define DEFAULT_TEXTURE_PATH_8				FILE_PATH_RELATIVE("Textures\\checkboard.dds")
#define DEFAULT_TEXTURE_PATH_9				FILE_PATH_RELATIVE("Textures\\ice.dds")
#define DEFAULT_TEXTURE_PATH_10				FILE_PATH_RELATIVE("Textures\\white1x1.dds")
#define DEFAULT_TEXTURE_PATH_11				FILE_PATH_RELATIVE("Textures\\WoodCrate01.dds")
#define DEFAULT_TEXTURE_PATH_12				FILE_PATH_RELATIVE("Textures\\grasscube1024.dds")
#define DEFAULT_TEXTURE_PATH_13				FILE_PATH_RELATIVE("Textures\\bricks2.dds")
#define DEFAULT_TEXTURE_PATH_14				FILE_PATH_RELATIVE("Textures\\bricks2_nmap.dds")
#define DEFAULT_TEXTURE_PATH_15				FILE_PATH_RELATIVE("Textures\\tile_nmap.dds")
#define DEFAULT_TEXTURE_PATH_16				FILE_PATH_RELATIVE("Textures\\default_nmap.dds")
#define DEFAULT_TEXTURE_PATH_17				FILE_PATH_RELATIVE("Textures\\snowcube1024.dds")
#define DEFAULT_TEXTURE_PATH_18				FILE_PATH_RELATIVE("Textures\\desertcube1024.dds")

#define DEFAULT_MODEL_PATH_1				FILE_PATH_RELATIVE("Models\\skull.txt")
#define DEFAULT_MODEL_PATH_2				FILE_PATH_RELATIVE("Models\\car.txt")
#define DEFAULT_MODEL_PATH_3				FILE_PATH_RELATIVE("Models\\soldier.m3d")